name: Update README.md

on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build the README.md
        run: python build_readme.py
      - name: Commit and push
        run: |
          git config --global user.name "Rafael Sanabria"
          git config --global user.email "rafael.d.sanabria@gmail.com"
          git diff --name-only
          git add README.md
          git diff --staged --quiet || git commit -m "Update README.md"
          git push